name: ec-tools
channels:
  - conda-forge
dependencies:
  - linkchecker
  - myst-parser
  - myst-nb
  - numba
  - numpy
  - pip
  - pytest
  - pytest-doctestplus
  - pythran
  - ruff
  - scipy
  - sphinx
  - sphinxcontrib-bibtex
  - sphinx-autobuild
  - sphinx_rtd_theme
  - transonic
  - pip:
    - sphinxcontrib.katex
