name: ec-tools

channels:
  - conda-forge
  - defaults
dependencies:
  - black
  - isort
  - maturin>=1.5,<2.0
  - myst-parser
  - myst-nb
  - numba
  - numpy
  - pip
  - pylint
  - pytest
  - pytest-doctestplus
  - pythran
  - scipy
  - sphinx
  - sphinxcontrib-bibtex
  - sphinx-autobuild
  - transonic
  - pip:
    - linkchecker
    - sphinx_rtd_theme
    - sphinxcontrib.katex
