# inspired by the pylint repo
[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "ec-tools"
license     = {text = "GPL-3.0-or-later"}
description = "tools to work with electrochemical data"
readme      = "README.md"

requires-python = ">=3.9.0"
dependencies    = [
    "numpy",
]
version = "0.0.2"

[tool.setuptools]
license-files = ["LICENSE"]  # Keep in sync with setup.cfg
