# inspired by the pylint repo
[build-system]
requires = ["maturin>=0.13,<0.14"]
build-backend = "maturin"

[project]
name = "ec-tools"
license     = {text = "GPL-3.0-or-later"}
description = "tools to work with electrochemical data"
readme      = "README.md"

requires-python = ">=3.9.0"
dependencies    = [
    "numpy",
    "transonic",
]
version = "0.0.1"

[tool.setuptools]
license-files = ["LICENSE"]  # Keep in sync with setup.cfg
