name: Test
on:
  push: { branches: [ "main" ] }
  pull_request: { branches: [ "main" ] }

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python: ["3.9", "3.10"]
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        source: ["conda", "pip"]
    steps:
      - uses: actions/checkout@v2
        with: { submodules: recursive }
      - uses: conda-incubator/setup-miniconda@v2
        with: { mamba-version: "*", channels: "conda-forge", channel-priority: true, python-version: "${{ matrix.python }}" }
      - name: install dependencies
        shell: bash -l {0}
        run: |
          mamba env update --quiet -n test -f environment.yml
          conda list
        if: ${{ matrix.source == 'conda' }}
      - name: install ec-tools
        shell: bash -l {0}
        run: |
          pip install --no-dependencies .
        if: ${{ matrix.source == 'conda' }}
      - name: install ec-tools
        shell: bash -l {0}
        run: |
          pip install .
        if: ${{ matrix.source == 'pip' }}
      - name: doctest
        shell: bash -l {0}
        run: |
          pytest --doctest-modules ec_tools
        if: ${{ matrix.source == 'conda' }}
